Postgresql
ShevchenyaIlya/itechart-pylab-2021 pull request #3
Opened 2021-01-26 19:31 UTC by ShevchenyaIlya

2021-01-29 09:10 UTC, alexkudelin commented on assignment2/postgresql_database.py
>      def create_tables(self):
Я думаю, что этот метод нужно сделать частью скрипта настройки БД. Подразумевается, что в коде идет работа с уже настроенной БД. Для ее настройки нужно завести отдельный скрипт (думаю, шелл-скрипт)

2021-01-29 09:12 UTC, alexkudelin commented on assignment2/db_connection_setting.json
> +  "password": "Sheva07012001",
Надеюсь, этот пароль используется только здесь :)

2021-01-29 09:31 UTC, alexkudelin commented on assignment2/postgresql_database.py
> +                "INSERT INTO users(username, user_karma, user_cake_day, post_karma, comment_karma) "
А чего остальные SQL-скрипты в файлы не убрал, как например `create_posts_table.sql`? Идея-то отличная -- хранить шаблоны скриптов в файлах и **при необходимости** их читать из файлов и работать с ними

2021-01-29 09:33 UTC, alexkudelin commented on assignment2/postgresql_database.py
> +        self.cursor.execute("SELECT * FROM users WHERE username=%s", (username,))
`SELECT * FROM users WHERE username=%s` --> `SELECT exists(SELECT user_id FROM users WHERE username=%s)`

2021-01-29 09:35 UTC, alexkudelin commented on assignment2/sql/create_posts_table.sql
> +    unique_id CHAR(32) UNIQUE NOT NULL,
`uuid` вместо `char(32)`?

2021-01-29 09:35 UTC, alexkudelin commented on assignment2/sql/create_posts_table.sql
> +    post_id SMALLSERIAL PRIMARY KEY NOT NULL,
`SMALLSERIAL` --> `BIGSERIAL`

2021-01-29 09:37 UTC, alexkudelin commented on assignment2/sql/create_posts_table.sql
> +    comments_number VARCHAR(10) NOT NULL,
Если я правильно понимаю, то сейчас кол-во комментов и голосов пишется в формате типа "54k"? Может быть, стоит переделать в числа, просто будет некая погрешность. Потому что, если тебе, например, понадобится ранжировать по этим полям, то случится печальная история

2021-01-29 09:37 UTC, alexkudelin commented on assignment2/sql/create_posts_table.sql
> +    owner SMALLSERIAL REFERENCES users(user_id));
`SMALLSERIAL` --> `BIGSERIAL`

2021-01-29 09:37 UTC, alexkudelin commented on assignment2/sql/create_users_table.sql
> +    user_id SMALLSERIAL PRIMARY KEY NOT NULL,
`SMALLSERIAL` --> `BIGSERIAL`

2021-01-29 09:38 UTC, alexkudelin commented on assignment2/sql/create_users_table.sql
> +    user_karma VARCHAR(10) NOT NULL,
Тоже числом надо сделать

2021-01-29 09:38 UTC, alexkudelin commented on assignment2/sql/create_users_table.sql
> +    post_karma VARCHAR(10) NOT NULL,
Должно быть числом

2021-01-29 09:38 UTC, alexkudelin commented on assignment2/sql/create_users_table.sql
> +    comment_karma VARCHAR(10) NOT NULL);
Должно быть числом

2021-01-29 09:39 UTC, alexkudelin commented on assignment2/server.py
> +        if not self.database_handler.get_single_post(unique_id):
нужен метод is_exists с таким же аргументом, который будет возвращать true/false

2021-01-29 09:41 UTC, alexkudelin commented on assignment2/server.py
>              return 201, "Created", {unique_id: line_number}
Разве тут unique_id не должен содержать непосредственно unique_id? :)

2021-01-29 09:41 UTC, alexkudelin commented on assignment2/server.py
> +        if self.database_handler.get_single_post(unique_id):
if/else поменять местами

2021-01-29 09:41 UTC, alexkudelin requested changes
Написал комменатрии и замечания

2021-01-29 11:08 UTC, alexkudelin commented on assignment2/postgresql_database.py
> +    query_files = [
Может быть, стоит переделать предзагрузку при начале работы на подгрузку прямо внутри метода, чтобы избежать паразитных чтений?

2021-01-29 11:12 UTC, ShevchenyaIlya commented on assignment2/server.py
>              return 201, "Created", {unique_id: line_number}
@alexkudelin Так было в задании: "в случае успеха возвращает код операции 201, а так же JSON формата {<UNIQUE_ID>: номер вставленной строки} "

2021-01-29 11:14 UTC, ShevchenyaIlya commented on assignment2/postgresql_database.py
> +    query_files = [
@alexkudelin Получиться, что каждый раз при вызове какого-то метода будет загружаться скрипт.

2021-01-29 11:33 UTC, alexkudelin commented on assignment2/postgresql_database.py
> +    query_files = [
@ShevchenyaIlya ну это ведь наверно не хуже, чем загружать каждый раз все скрипты?

2021-01-29 11:35 UTC, alexkudelin commented on assignment2/server.py
>              return 201, "Created", {unique_id: line_number}
А, справедливо. Тогда да, все так

2021-01-30 17:44 UTC, alexkudelin commented on assignment2/postgresql_database.py
> +if __name__ == "__main__":
Вот это в конечном коде не нужно

2021-01-30 17:45 UTC, alexkudelin commented on assignment2/sql/create_posts_table.sql
> +CREATE TABLE IF NOT EXISTS posts(
Этот скрипт, видимо, по ошибке тут? См.: https://github.com/ShevchenyaIlya/itechart-pylab-2021/pull/5/files#r567280489

2021-01-30 17:46 UTC, alexkudelin commented on assignment2/sql/create_users_table.sql
> +CREATE TABLE IF NOT EXISTS users(
Аналогично: https://github.com/ShevchenyaIlya/itechart-pylab-2021/pull/5/files#r567280489

2021-01-30 17:47 UTC, alexkudelin commented on assignment2/convert_karma.py
> +def convert_post_numeric_fields(post_data: dict):
Если уже есть модуль с утилитами разного рода (перевод дат туда-сюда или еще что-то "утилитарное"), то нужно эти функции убрать туда. Иначе, надо переименовать этот файл в `converters.py`, например

2021-01-30 17:47 UTC, alexkudelin requested changes
Отписал в комментариях

2021-01-30 18:49 UTC, alexkudelin approved these changes
OK

2021-01-30 18:50 UTC, merged